version: "3"
services:
  edgedb:
    image: edgedb/edgedb:nightly
    environment:
      EDGEDB_SERVER_SECURITY: insecure_dev_mode
      EDGEDB_DEBUG_HTTP_INJECT_CORS: 1
      EDGEDB_SERVER_BIND_ADDRESS: 0.0.0.0
      EDGEDB_SERVER_PORT: 5656
    ports:
      - "5656:5656"
  studio:
    image: edgedb-studio
    environment:
      EDGEDB_HOST: edgedb
      EDGEDB_PORT: 5656
    ports:
      - "10780:80"
